language: ruby
rvm:
  - 2.4.1
install:
  - gem install system_cat
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rspec spec
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:drop db:create db:migrate
